// source: protobuf/data.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.datapb.SegmentData', null, global);
goog.exportSymbol('proto.datapb.SegmentedDataError', null, global);
goog.exportSymbol('proto.datapb.SegmentedDataErrorResponse', null, global);
goog.exportSymbol('proto.datapb.SegmentedTimelineCompareResponse', null, global);
goog.exportSymbol('proto.datapb.SegmentedTimelineDataRequest', null, global);
goog.exportSymbol('proto.datapb.SegmentedTimelineDataResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.datapb.SegmentedTimelineDataRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.datapb.SegmentedTimelineDataRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.datapb.SegmentedTimelineDataRequest.displayName = 'proto.datapb.SegmentedTimelineDataRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.datapb.SegmentData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.datapb.SegmentData.repeatedFields_, null);
};
goog.inherits(proto.datapb.SegmentData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.datapb.SegmentData.displayName = 'proto.datapb.SegmentData';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.datapb.SegmentedTimelineDataResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.datapb.SegmentedTimelineDataResponse.repeatedFields_, null);
};
goog.inherits(proto.datapb.SegmentedTimelineDataResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.datapb.SegmentedTimelineDataResponse.displayName = 'proto.datapb.SegmentedTimelineDataResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.datapb.SegmentedTimelineCompareResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.datapb.SegmentedTimelineCompareResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.datapb.SegmentedTimelineCompareResponse.displayName = 'proto.datapb.SegmentedTimelineCompareResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.datapb.SegmentedDataError = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.datapb.SegmentedDataError.repeatedFields_, null);
};
goog.inherits(proto.datapb.SegmentedDataError, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.datapb.SegmentedDataError.displayName = 'proto.datapb.SegmentedDataError';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.datapb.SegmentedDataErrorResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.datapb.SegmentedDataErrorResponse.repeatedFields_, null);
};
goog.inherits(proto.datapb.SegmentedDataErrorResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.datapb.SegmentedDataErrorResponse.displayName = 'proto.datapb.SegmentedDataErrorResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.datapb.SegmentedTimelineDataRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.datapb.SegmentedTimelineDataRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.datapb.SegmentedTimelineDataRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.datapb.SegmentedTimelineDataRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    filename: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.datapb.SegmentedTimelineDataRequest}
 */
proto.datapb.SegmentedTimelineDataRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.datapb.SegmentedTimelineDataRequest;
  return proto.datapb.SegmentedTimelineDataRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.datapb.SegmentedTimelineDataRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.datapb.SegmentedTimelineDataRequest}
 */
proto.datapb.SegmentedTimelineDataRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFilename(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.datapb.SegmentedTimelineDataRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.datapb.SegmentedTimelineDataRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.datapb.SegmentedTimelineDataRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.datapb.SegmentedTimelineDataRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFilename();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string filename = 1;
 * @return {string}
 */
proto.datapb.SegmentedTimelineDataRequest.prototype.getFilename = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.datapb.SegmentedTimelineDataRequest} returns this
 */
proto.datapb.SegmentedTimelineDataRequest.prototype.setFilename = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.datapb.SegmentData.repeatedFields_ = [3,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.datapb.SegmentData.prototype.toObject = function(opt_includeInstance) {
  return proto.datapb.SegmentData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.datapb.SegmentData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.datapb.SegmentData.toObject = function(includeInstance, msg) {
  var f, obj = {
    country: jspb.Message.getFieldWithDefault(msg, 1, ""),
    device: jspb.Message.getFieldWithDefault(msg, 2, ""),
    datesList: jspb.Message.toObjectList(msg.getDatesList(),
    google_protobuf_timestamp_pb.Timestamp.toObject, includeInstance),
    inventoryVolumesList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.datapb.SegmentData}
 */
proto.datapb.SegmentData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.datapb.SegmentData;
  return proto.datapb.SegmentData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.datapb.SegmentData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.datapb.SegmentData}
 */
proto.datapb.SegmentData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCountry(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDevice(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.addDates(value);
      break;
    case 4:
      var value = /** @type {!Array<number>} */ (reader.readPackedInt32());
      msg.setInventoryVolumesList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.datapb.SegmentData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.datapb.SegmentData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.datapb.SegmentData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.datapb.SegmentData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCountry();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDevice();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDatesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getInventoryVolumesList();
  if (f.length > 0) {
    writer.writePackedInt32(
      4,
      f
    );
  }
};


/**
 * optional string country = 1;
 * @return {string}
 */
proto.datapb.SegmentData.prototype.getCountry = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.datapb.SegmentData} returns this
 */
proto.datapb.SegmentData.prototype.setCountry = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string device = 2;
 * @return {string}
 */
proto.datapb.SegmentData.prototype.getDevice = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.datapb.SegmentData} returns this
 */
proto.datapb.SegmentData.prototype.setDevice = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated google.protobuf.Timestamp dates = 3;
 * @return {!Array<!proto.google.protobuf.Timestamp>}
 */
proto.datapb.SegmentData.prototype.getDatesList = function() {
  return /** @type{!Array<!proto.google.protobuf.Timestamp>} */ (
    jspb.Message.getRepeatedWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {!Array<!proto.google.protobuf.Timestamp>} value
 * @return {!proto.datapb.SegmentData} returns this
*/
proto.datapb.SegmentData.prototype.setDatesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.google.protobuf.Timestamp=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.protobuf.Timestamp}
 */
proto.datapb.SegmentData.prototype.addDates = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.google.protobuf.Timestamp, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.datapb.SegmentData} returns this
 */
proto.datapb.SegmentData.prototype.clearDatesList = function() {
  return this.setDatesList([]);
};


/**
 * repeated int32 inventory_volumes = 4;
 * @return {!Array<number>}
 */
proto.datapb.SegmentData.prototype.getInventoryVolumesList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 4));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.datapb.SegmentData} returns this
 */
proto.datapb.SegmentData.prototype.setInventoryVolumesList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.datapb.SegmentData} returns this
 */
proto.datapb.SegmentData.prototype.addInventoryVolumes = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.datapb.SegmentData} returns this
 */
proto.datapb.SegmentData.prototype.clearInventoryVolumesList = function() {
  return this.setInventoryVolumesList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.datapb.SegmentedTimelineDataResponse.repeatedFields_ = [1,2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.datapb.SegmentedTimelineDataResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.datapb.SegmentedTimelineDataResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.datapb.SegmentedTimelineDataResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.datapb.SegmentedTimelineDataResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    dataList: jspb.Message.toObjectList(msg.getDataList(),
    proto.datapb.SegmentData.toObject, includeInstance),
    countriesList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.datapb.SegmentedTimelineDataResponse}
 */
proto.datapb.SegmentedTimelineDataResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.datapb.SegmentedTimelineDataResponse;
  return proto.datapb.SegmentedTimelineDataResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.datapb.SegmentedTimelineDataResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.datapb.SegmentedTimelineDataResponse}
 */
proto.datapb.SegmentedTimelineDataResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.datapb.SegmentData;
      reader.readMessage(value,proto.datapb.SegmentData.deserializeBinaryFromReader);
      msg.addData(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addCountries(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.datapb.SegmentedTimelineDataResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.datapb.SegmentedTimelineDataResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.datapb.SegmentedTimelineDataResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.datapb.SegmentedTimelineDataResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDataList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.datapb.SegmentData.serializeBinaryToWriter
    );
  }
  f = message.getCountriesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
};


/**
 * repeated SegmentData data = 1;
 * @return {!Array<!proto.datapb.SegmentData>}
 */
proto.datapb.SegmentedTimelineDataResponse.prototype.getDataList = function() {
  return /** @type{!Array<!proto.datapb.SegmentData>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.datapb.SegmentData, 1));
};


/**
 * @param {!Array<!proto.datapb.SegmentData>} value
 * @return {!proto.datapb.SegmentedTimelineDataResponse} returns this
*/
proto.datapb.SegmentedTimelineDataResponse.prototype.setDataList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.datapb.SegmentData=} opt_value
 * @param {number=} opt_index
 * @return {!proto.datapb.SegmentData}
 */
proto.datapb.SegmentedTimelineDataResponse.prototype.addData = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.datapb.SegmentData, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.datapb.SegmentedTimelineDataResponse} returns this
 */
proto.datapb.SegmentedTimelineDataResponse.prototype.clearDataList = function() {
  return this.setDataList([]);
};


/**
 * repeated string countries = 2;
 * @return {!Array<string>}
 */
proto.datapb.SegmentedTimelineDataResponse.prototype.getCountriesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.datapb.SegmentedTimelineDataResponse} returns this
 */
proto.datapb.SegmentedTimelineDataResponse.prototype.setCountriesList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.datapb.SegmentedTimelineDataResponse} returns this
 */
proto.datapb.SegmentedTimelineDataResponse.prototype.addCountries = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.datapb.SegmentedTimelineDataResponse} returns this
 */
proto.datapb.SegmentedTimelineDataResponse.prototype.clearCountriesList = function() {
  return this.setCountriesList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.datapb.SegmentedTimelineCompareResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.datapb.SegmentedTimelineCompareResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.datapb.SegmentedTimelineCompareResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.datapb.SegmentedTimelineCompareResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    originalData: (f = msg.getOriginalData()) && proto.datapb.SegmentedTimelineDataResponse.toObject(includeInstance, f),
    comparisonData: (f = msg.getComparisonData()) && proto.datapb.SegmentedTimelineDataResponse.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.datapb.SegmentedTimelineCompareResponse}
 */
proto.datapb.SegmentedTimelineCompareResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.datapb.SegmentedTimelineCompareResponse;
  return proto.datapb.SegmentedTimelineCompareResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.datapb.SegmentedTimelineCompareResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.datapb.SegmentedTimelineCompareResponse}
 */
proto.datapb.SegmentedTimelineCompareResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.datapb.SegmentedTimelineDataResponse;
      reader.readMessage(value,proto.datapb.SegmentedTimelineDataResponse.deserializeBinaryFromReader);
      msg.setOriginalData(value);
      break;
    case 2:
      var value = new proto.datapb.SegmentedTimelineDataResponse;
      reader.readMessage(value,proto.datapb.SegmentedTimelineDataResponse.deserializeBinaryFromReader);
      msg.setComparisonData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.datapb.SegmentedTimelineCompareResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.datapb.SegmentedTimelineCompareResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.datapb.SegmentedTimelineCompareResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.datapb.SegmentedTimelineCompareResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOriginalData();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.datapb.SegmentedTimelineDataResponse.serializeBinaryToWriter
    );
  }
  f = message.getComparisonData();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.datapb.SegmentedTimelineDataResponse.serializeBinaryToWriter
    );
  }
};


/**
 * optional SegmentedTimelineDataResponse original_data = 1;
 * @return {?proto.datapb.SegmentedTimelineDataResponse}
 */
proto.datapb.SegmentedTimelineCompareResponse.prototype.getOriginalData = function() {
  return /** @type{?proto.datapb.SegmentedTimelineDataResponse} */ (
    jspb.Message.getWrapperField(this, proto.datapb.SegmentedTimelineDataResponse, 1));
};


/**
 * @param {?proto.datapb.SegmentedTimelineDataResponse|undefined} value
 * @return {!proto.datapb.SegmentedTimelineCompareResponse} returns this
*/
proto.datapb.SegmentedTimelineCompareResponse.prototype.setOriginalData = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.datapb.SegmentedTimelineCompareResponse} returns this
 */
proto.datapb.SegmentedTimelineCompareResponse.prototype.clearOriginalData = function() {
  return this.setOriginalData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.datapb.SegmentedTimelineCompareResponse.prototype.hasOriginalData = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional SegmentedTimelineDataResponse comparison_data = 2;
 * @return {?proto.datapb.SegmentedTimelineDataResponse}
 */
proto.datapb.SegmentedTimelineCompareResponse.prototype.getComparisonData = function() {
  return /** @type{?proto.datapb.SegmentedTimelineDataResponse} */ (
    jspb.Message.getWrapperField(this, proto.datapb.SegmentedTimelineDataResponse, 2));
};


/**
 * @param {?proto.datapb.SegmentedTimelineDataResponse|undefined} value
 * @return {!proto.datapb.SegmentedTimelineCompareResponse} returns this
*/
proto.datapb.SegmentedTimelineCompareResponse.prototype.setComparisonData = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.datapb.SegmentedTimelineCompareResponse} returns this
 */
proto.datapb.SegmentedTimelineCompareResponse.prototype.clearComparisonData = function() {
  return this.setComparisonData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.datapb.SegmentedTimelineCompareResponse.prototype.hasComparisonData = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.datapb.SegmentedDataError.repeatedFields_ = [3,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.datapb.SegmentedDataError.prototype.toObject = function(opt_includeInstance) {
  return proto.datapb.SegmentedDataError.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.datapb.SegmentedDataError} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.datapb.SegmentedDataError.toObject = function(includeInstance, msg) {
  var f, obj = {
    country: jspb.Message.getFieldWithDefault(msg, 1, ""),
    device: jspb.Message.getFieldWithDefault(msg, 2, ""),
    datesList: jspb.Message.toObjectList(msg.getDatesList(),
    google_protobuf_timestamp_pb.Timestamp.toObject, includeInstance),
    errorList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 4)) == null ? undefined : f,
    min: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
    max: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0),
    median: jspb.Message.getFloatingPointFieldWithDefault(msg, 7, 0.0),
    firstQuartile: jspb.Message.getFloatingPointFieldWithDefault(msg, 8, 0.0),
    thirdQuartile: jspb.Message.getFloatingPointFieldWithDefault(msg, 9, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.datapb.SegmentedDataError}
 */
proto.datapb.SegmentedDataError.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.datapb.SegmentedDataError;
  return proto.datapb.SegmentedDataError.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.datapb.SegmentedDataError} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.datapb.SegmentedDataError}
 */
proto.datapb.SegmentedDataError.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCountry(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDevice(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.addDates(value);
      break;
    case 4:
      var value = /** @type {!Array<number>} */ (reader.readPackedFloat());
      msg.setErrorList(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setMin(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setMax(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setMedian(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setFirstQuartile(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setThirdQuartile(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.datapb.SegmentedDataError.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.datapb.SegmentedDataError.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.datapb.SegmentedDataError} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.datapb.SegmentedDataError.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCountry();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDevice();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDatesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getErrorList();
  if (f.length > 0) {
    writer.writePackedFloat(
      4,
      f
    );
  }
  f = message.getMin();
  if (f !== 0.0) {
    writer.writeFloat(
      5,
      f
    );
  }
  f = message.getMax();
  if (f !== 0.0) {
    writer.writeFloat(
      6,
      f
    );
  }
  f = message.getMedian();
  if (f !== 0.0) {
    writer.writeFloat(
      7,
      f
    );
  }
  f = message.getFirstQuartile();
  if (f !== 0.0) {
    writer.writeFloat(
      8,
      f
    );
  }
  f = message.getThirdQuartile();
  if (f !== 0.0) {
    writer.writeFloat(
      9,
      f
    );
  }
};


/**
 * optional string country = 1;
 * @return {string}
 */
proto.datapb.SegmentedDataError.prototype.getCountry = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.datapb.SegmentedDataError} returns this
 */
proto.datapb.SegmentedDataError.prototype.setCountry = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string device = 2;
 * @return {string}
 */
proto.datapb.SegmentedDataError.prototype.getDevice = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.datapb.SegmentedDataError} returns this
 */
proto.datapb.SegmentedDataError.prototype.setDevice = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated google.protobuf.Timestamp dates = 3;
 * @return {!Array<!proto.google.protobuf.Timestamp>}
 */
proto.datapb.SegmentedDataError.prototype.getDatesList = function() {
  return /** @type{!Array<!proto.google.protobuf.Timestamp>} */ (
    jspb.Message.getRepeatedWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {!Array<!proto.google.protobuf.Timestamp>} value
 * @return {!proto.datapb.SegmentedDataError} returns this
*/
proto.datapb.SegmentedDataError.prototype.setDatesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.google.protobuf.Timestamp=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.protobuf.Timestamp}
 */
proto.datapb.SegmentedDataError.prototype.addDates = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.google.protobuf.Timestamp, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.datapb.SegmentedDataError} returns this
 */
proto.datapb.SegmentedDataError.prototype.clearDatesList = function() {
  return this.setDatesList([]);
};


/**
 * repeated float error = 4;
 * @return {!Array<number>}
 */
proto.datapb.SegmentedDataError.prototype.getErrorList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 4));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.datapb.SegmentedDataError} returns this
 */
proto.datapb.SegmentedDataError.prototype.setErrorList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.datapb.SegmentedDataError} returns this
 */
proto.datapb.SegmentedDataError.prototype.addError = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.datapb.SegmentedDataError} returns this
 */
proto.datapb.SegmentedDataError.prototype.clearErrorList = function() {
  return this.setErrorList([]);
};


/**
 * optional float min = 5;
 * @return {number}
 */
proto.datapb.SegmentedDataError.prototype.getMin = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.datapb.SegmentedDataError} returns this
 */
proto.datapb.SegmentedDataError.prototype.setMin = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional float max = 6;
 * @return {number}
 */
proto.datapb.SegmentedDataError.prototype.getMax = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.datapb.SegmentedDataError} returns this
 */
proto.datapb.SegmentedDataError.prototype.setMax = function(value) {
  return jspb.Message.setProto3FloatField(this, 6, value);
};


/**
 * optional float median = 7;
 * @return {number}
 */
proto.datapb.SegmentedDataError.prototype.getMedian = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 7, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.datapb.SegmentedDataError} returns this
 */
proto.datapb.SegmentedDataError.prototype.setMedian = function(value) {
  return jspb.Message.setProto3FloatField(this, 7, value);
};


/**
 * optional float first_quartile = 8;
 * @return {number}
 */
proto.datapb.SegmentedDataError.prototype.getFirstQuartile = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 8, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.datapb.SegmentedDataError} returns this
 */
proto.datapb.SegmentedDataError.prototype.setFirstQuartile = function(value) {
  return jspb.Message.setProto3FloatField(this, 8, value);
};


/**
 * optional float third_quartile = 9;
 * @return {number}
 */
proto.datapb.SegmentedDataError.prototype.getThirdQuartile = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 9, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.datapb.SegmentedDataError} returns this
 */
proto.datapb.SegmentedDataError.prototype.setThirdQuartile = function(value) {
  return jspb.Message.setProto3FloatField(this, 9, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.datapb.SegmentedDataErrorResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.datapb.SegmentedDataErrorResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.datapb.SegmentedDataErrorResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.datapb.SegmentedDataErrorResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.datapb.SegmentedDataErrorResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    errorsList: jspb.Message.toObjectList(msg.getErrorsList(),
    proto.datapb.SegmentedDataError.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.datapb.SegmentedDataErrorResponse}
 */
proto.datapb.SegmentedDataErrorResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.datapb.SegmentedDataErrorResponse;
  return proto.datapb.SegmentedDataErrorResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.datapb.SegmentedDataErrorResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.datapb.SegmentedDataErrorResponse}
 */
proto.datapb.SegmentedDataErrorResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.datapb.SegmentedDataError;
      reader.readMessage(value,proto.datapb.SegmentedDataError.deserializeBinaryFromReader);
      msg.addErrors(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.datapb.SegmentedDataErrorResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.datapb.SegmentedDataErrorResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.datapb.SegmentedDataErrorResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.datapb.SegmentedDataErrorResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getErrorsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.datapb.SegmentedDataError.serializeBinaryToWriter
    );
  }
};


/**
 * repeated SegmentedDataError errors = 1;
 * @return {!Array<!proto.datapb.SegmentedDataError>}
 */
proto.datapb.SegmentedDataErrorResponse.prototype.getErrorsList = function() {
  return /** @type{!Array<!proto.datapb.SegmentedDataError>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.datapb.SegmentedDataError, 1));
};


/**
 * @param {!Array<!proto.datapb.SegmentedDataError>} value
 * @return {!proto.datapb.SegmentedDataErrorResponse} returns this
*/
proto.datapb.SegmentedDataErrorResponse.prototype.setErrorsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.datapb.SegmentedDataError=} opt_value
 * @param {number=} opt_index
 * @return {!proto.datapb.SegmentedDataError}
 */
proto.datapb.SegmentedDataErrorResponse.prototype.addErrors = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.datapb.SegmentedDataError, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.datapb.SegmentedDataErrorResponse} returns this
 */
proto.datapb.SegmentedDataErrorResponse.prototype.clearErrorsList = function() {
  return this.setErrorsList([]);
};


goog.object.extend(exports, proto.datapb);
